import '../models/category_product.dart';

class CategoryProductsData {
  static final Map<String, List<CategoryProduct>> products = {
    'leafy green': [
      const CategoryProduct(
        id: '1',
        name: 'Fresh Spinach',
        imageUrl: 'assets/images/tomato.png',
        price: 30,
        originalPrice: 40,
        unit: '250g',
        discount: '20% OFF',
        category: 'Grocery & Kitchen',
        subCategory: 'leafy green',
      ),
    ],
    'cruciferous': [
      const CategoryProduct(
        id: '2',
        name: 'Fresh Broccoli',
        imageUrl: 'assets/images/tomato.png',
        price: 80,
        originalPrice: 100,
        unit: '500g',
        discount: '20% OFF',
        category: 'Grocery & Kitchen',
        subCategory: 'cruciferous',
      ),
    ],
    'allium': [
      const CategoryProduct(
        id: '3',
        name: 'Fresh Onion',
        imageUrl: 'assets/images/tomato.png',
        price: 40,
        originalPrice: 50,
        unit: '1kg',
        discount: '20% OFF',
        category: 'Grocery & Kitchen',
        subCategory: 'allium',
      ),
    ],
    'root': [
      const CategoryProduct(
        id: '4',
        name: 'Fresh Potato',
        imageUrl: 'assets/images/tomato.png',
        price: 35,
        originalPrice: 45,
        unit: '1kg',
        discount: '20% OFF',
        category: 'Grocery & Kitchen',
        subCategory: 'root',
      ),
    ],
    'Vegetables & Fruits': [
      const CategoryProduct(
        id: '1',
        name: 'Desi Tomato (Nattu Thakkali)',
        imageUrl: 'assets/images/tomato.png',
        price: 42,
        originalPrice: 58,
        unit: '1kg',
        discount: '20% OFF',
        category: 'Grocery & Kitchen',
        subCategory: 'Vegetables & Fruits',
      ),
      const CategoryProduct(
        id: '2',
        name: 'Fresh Apple',
        imageUrl: 'assets/images/apple.png',
        price: 120,
        originalPrice: 150,
        unit: '1kg',
        discount: '20% OFF',
        category: 'Grocery & Kitchen',
        subCategory: 'Vegetables & Fruits',
      ),
      const CategoryProduct(
        id: '3',
        name: 'Fresh Banana',
        imageUrl: 'assets/images/banana.png',
        price: 60,
        originalPrice: 75,
        unit: '1kg',
        discount: '20% OFF',
        category: 'Grocery & Kitchen',
        subCategory: 'Vegetables & Fruits',
      ),
      const CategoryProduct(
        id: '4',
        name: 'Fresh Ginger',
        imageUrl: 'assets/images/ginger.png',
        price: 35,
        originalPrice: 45,
        unit: '250g',
        discount: '20% OFF',
        category: 'Grocery & Kitchen',
        subCategory: 'Vegetables & Fruits',
      ),
    ],
  };
}
